'use client';

import React from 'react';
import { motion } from 'framer-motion';
import { Card } from '@/components/ui/Card';
import { XCircle, CheckCircle2, TrendingDown, Clock, ShieldCheck, Zap } from 'lucide-react';

export const WhyChooseSection: React.FC = () => {
  return (
    <section className="py-24 bg-white dark:bg-slate-900/40 border-y border-slate-200/80 dark:border-slate-800/80 transition-colors duration-300 relative">
      <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 space-y-16">
        <div className="text-center space-y-4 max-w-3xl mx-auto">
          <h2 className="text-xs font-mono font-bold text-blue-600 dark:text-cyan-400 uppercase tracking-widest">
            Traditional vs AI Automation
          </h2>
          <h3 className="text-3xl sm:text-5xl font-black text-slate-900 dark:text-white tracking-tight">
            Why Choose Runbook Following Agent?
          </h3>
          <p className="text-sm sm:text-base text-slate-600 dark:text-slate-400 leading-relaxed font-medium">
            Eliminate 2 AM human stress and operational errors with deterministic, safe AI execution.
          </p>
        </div>

        {/* Comparison Grid */}
        <div className="grid grid-cols-1 lg:grid-cols-2 gap-8">
          {/* Traditional Method */}
          <Card className="p-8 border-rose-200 dark:border-rose-500/30 bg-rose-50/60 dark:bg-rose-950/10 space-y-6">
            <div className="flex items-center gap-3 pb-4 border-b border-rose-200 dark:border-rose-500/20">
              <XCircle className="h-7 w-7 text-rose-600 dark:text-rose-400 shrink-0" />
              <div>
                <h4 className="font-extrabold text-slate-900 dark:text-white text-xl">Traditional SRE Workflow</h4>
                <p className="text-xs text-rose-700 dark:text-rose-300 font-mono font-bold">Manual • Error Prone • Stressful</p>
              </div>
            </div>

            <ul className="space-y-4 text-xs sm:text-sm text-slate-700 dark:text-slate-300 font-medium">
              <li className="flex items-start gap-3">
                <XCircle className="h-4 w-4 text-rose-500 shrink-0 mt-0.5" />
                <span>Takes 20–40 minutes to locate and read 40-page PDF runbooks at 2 AM.</span>
              </li>
              <li className="flex items-start gap-3">
                <XCircle className="h-4 w-4 text-rose-500 shrink-0 mt-0.5" />
                <span>Human errors, skipped preconditions, or wrong command syntax executed on prod.</span>
              </li>
              <li className="flex items-start gap-3">
                <XCircle className="h-4 w-4 text-rose-500 shrink-0 mt-0.5" />
                <span>Inconsistent steps followed across different engineers on shift.</span>
              </li>
              <li className="flex items-start gap-3">
                <XCircle className="h-4 w-4 text-rose-500 shrink-0 mt-0.5" />
                <span>Manual ticket logging and delayed post-incident report writing.</span>
              </li>
            </ul>
          </Card>

          {/* AI Method */}
          <Card className="p-8 border-emerald-200 dark:border-emerald-500/30 bg-emerald-50/60 dark:bg-emerald-950/10 space-y-6">
            <div className="flex items-center gap-3 pb-4 border-b border-emerald-200 dark:border-emerald-500/20">
              <CheckCircle2 className="h-7 w-7 text-emerald-600 dark:text-emerald-400 shrink-0" />
              <div>
                <h4 className="font-extrabold text-slate-900 dark:text-white text-xl">AI Agent Workflow</h4>
                <p className="text-xs text-emerald-700 dark:text-emerald-300 font-mono font-bold">3-Minute MTTR • Safe • Enterprise Ready</p>
              </div>
            </div>

            <ul className="space-y-4 text-xs sm:text-sm text-slate-700 dark:text-slate-300 font-medium">
              <li className="flex items-start gap-3">
                <CheckCircle2 className="h-4 w-4 text-emerald-500 shrink-0 mt-0.5" />
                <span>Instant retrieval of exact procedure section using ChromaDB RAG.</span>
              </li>
              <li className="flex items-start gap-3">
                <CheckCircle2 className="h-4 w-4 text-emerald-500 shrink-0 mt-0.5" />
                <span>Automated safe shell execution with SRE approval triggers for risky commands.</span>
              </li>
              <li className="flex items-start gap-3">
                <CheckCircle2 className="h-4 w-4 text-emerald-500 shrink-0 mt-0.5" />
                <span>Standardized, deterministic execution graph generated by LangGraph.</span>
              </li>
              <li className="flex items-start gap-3">
                <CheckCircle2 className="h-4 w-4 text-emerald-500 shrink-0 mt-0.5" />
                <span>Automated PDF incident resolution reports created upon resolution.</span>
              </li>
            </ul>
          </Card>
        </div>

        {/* Key Statistics Highlights */}
        <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-4 gap-6 pt-6">
          <div className="p-6 rounded-2xl bg-slate-100/70 dark:bg-slate-900 border border-slate-200/80 dark:border-slate-800 text-center space-y-2">
            <div className="flex justify-center text-blue-600 dark:text-blue-400">
              <Clock className="h-8 w-8" />
            </div>
            <h3 className="text-3xl font-black text-slate-900 dark:text-white">3.2 Mins</h3>
            <p className="text-xs text-slate-500 dark:text-slate-400 font-medium">Average Incident MTTR</p>
          </div>

          <div className="p-6 rounded-2xl bg-slate-100/70 dark:bg-slate-900 border border-slate-200/80 dark:border-slate-800 text-center space-y-2">
            <div className="flex justify-center text-emerald-600 dark:text-emerald-400">
              <TrendingDown className="h-8 w-8" />
            </div>
            <h3 className="text-3xl font-black text-slate-900 dark:text-white">91% Lower</h3>
            <p className="text-xs text-slate-500 dark:text-slate-400 font-medium">Resolution Time Reduction</p>
          </div>

          <div className="p-6 rounded-2xl bg-slate-100/70 dark:bg-slate-900 border border-slate-200/80 dark:border-slate-800 text-center space-y-2">
            <div className="flex justify-center text-cyan-600 dark:text-cyan-400">
              <Zap className="h-8 w-8" />
            </div>
            <h3 className="text-3xl font-black text-slate-900 dark:text-white">97.8%</h3>
            <p className="text-xs text-slate-500 dark:text-slate-400 font-medium">RAG Chunk Accuracy</p>
          </div>

          <div className="p-6 rounded-2xl bg-slate-100/70 dark:bg-slate-900 border border-slate-200/80 dark:border-slate-800 text-center space-y-2">
            <div className="flex justify-center text-indigo-600 dark:text-indigo-400">
              <ShieldCheck className="h-8 w-8" />
            </div>
            <h3 className="text-3xl font-black text-slate-900 dark:text-white">100%</h3>
            <p className="text-xs text-slate-500 dark:text-slate-400 font-medium">Command Safety Compliance</p>
          </div>
        </div>
      </div>
    </section>
  );
};
