import React from 'react';
import { IncidentReport } from '@/types/report';
import { Badge } from '../ui/Badge';
import { Button } from '../ui/Button';
import { Download, CheckCircle2, ShieldCheck, Printer } from 'lucide-react';

export const PDFViewer: React.FC<{ report: IncidentReport }> = ({ report }) => {
  return (
    <div className="space-y-6 text-slate-200">
      {/* PDF Mock Document Container */}
      <div className="p-8 rounded-2xl bg-slate-950 border border-slate-800 space-y-6 shadow-2xl font-sans">
        {/* Header */}
        <div className="flex items-center justify-between border-b border-slate-800 pb-6">
          <div>
            <div className="flex items-center gap-2">
              <ShieldCheck className="h-6 w-6 text-blue-400" />
              <h2 className="text-xl font-bold text-white tracking-wide">INCIDENT RESOLUTION REPORT</h2>
            </div>
            <p className="text-xs text-slate-400 mt-1 font-mono">Document Ref: {report.id} | Generated by AI Reporter Agent</p>
          </div>
          <Badge variant="success" size="md">{report.status}</Badge>
        </div>

        {/* Overview Grid */}
        <div className="grid grid-cols-2 sm:grid-cols-4 gap-4 p-4 rounded-xl bg-slate-900/60 border border-slate-800 text-xs">
          <div>
            <span className="text-[10px] text-slate-500 uppercase tracking-wider block">Incident ID</span>
            <span className="font-mono font-bold text-white">{report.incidentId}</span>
          </div>
          <div>
            <span className="text-[10px] text-slate-500 uppercase tracking-wider block">Severity</span>
            <span className="font-bold text-rose-400">{report.severity}</span>
          </div>
          <div>
            <span className="text-[10px] text-slate-500 uppercase tracking-wider block">Resolution Time</span>
            <span className="font-mono text-emerald-400">{report.duration}</span>
          </div>
          <div>
            <span className="text-[10px] text-slate-500 uppercase tracking-wider block">Authorized By</span>
            <span className="text-slate-300 font-semibold">{report.resolvedBy}</span>
          </div>
        </div>

        {/* Issue & Executive Summary */}
        <div className="space-y-2">
          <h4 className="text-xs font-bold text-slate-400 uppercase tracking-wider">Root Cause & Alert Summary</h4>
          <p className="text-sm font-semibold text-white">{report.issue}</p>
          <div className="p-4 rounded-xl bg-slate-900/40 border border-slate-800/80 text-xs text-slate-300 leading-relaxed">
            {report.summary}
          </div>
        </div>

        {/* Steps Executed Audit Trail */}
        <div className="space-y-3">
          <h4 className="text-xs font-bold text-slate-400 uppercase tracking-wider">Audit Log of Shell Execution ({report.executedStepsCount} steps)</h4>
          <div className="space-y-2 font-mono text-xs">
            <div className="p-2.5 rounded-lg bg-slate-900 border border-slate-800 flex items-center justify-between text-emerald-400">
              <span>Step 1: systemctl status postgresql</span>
              <span className="text-[10px] text-slate-500">PASSED [0.8s]</span>
            </div>
            <div className="p-2.5 rounded-lg bg-slate-900 border border-slate-800 flex items-center justify-between text-emerald-400">
              <span>Step 2: df -h /var/lib/postgresql</span>
              <span className="text-[10px] text-slate-500">PASSED [0.4s]</span>
            </div>
            <div className="p-2.5 rounded-lg bg-slate-900 border border-slate-800 flex items-center justify-between text-amber-400">
              <span>Step 3: systemctl restart postgresql (Human Authorized)</span>
              <span className="text-[10px] text-slate-500">APPROVED [2.1s]</span>
            </div>
          </div>
        </div>
      </div>

      <div className="flex items-center justify-end gap-3">
        <Button variant="outline" size="md" leftIcon={<Printer className="h-4 w-4" />}>
          Print Executive Report
        </Button>
        <Button variant="glow" size="md" leftIcon={<Download className="h-4 w-4" />}>
          Download Standard PDF
        </Button>
      </div>
    </div>
  );
};
