package com.resolvex.ai.model;

public enum NotificationType {
    INCIDENT_CREATED,
    INCIDENT_UPDATED,
    INCIDENT_RESOLVED,
    INCIDENT_ASSIGNED,
    WORKFLOW_CREATED,
    WORKFLOW_APPROVED,
    ESCALATION_CREATED,
    CHAT_REPLY,
    SYSTEM_ALERT,
    RUNBOOK_UPLOAD,
    REPORT_GENERATED,
    AI_FAILURE,
    COMMAND_FAILURE,
    SYSTEM_WARNING
}
